name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Install deps
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update
          sudo apt-get install -y cmake gcc-multilib g++-multilib
      - name: Build
        run: |
          mkdir build && cd build
          cmake .. -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32 -DCMAKE_BUILD_TYPE=Release
          cmake --build . --config Release
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: sampvoice-linux
          path: build/**/*.so
